services:
    stock_importer.stock_impoter:
        class: AppBundle\Service\StockImporter
        arguments:
            - '@stock_importer.stock_repository'
        calls:
            - [setLogger,['@stock_importer.logger.index']]
            - [addImporter,['@stock_importer.importer.nasdaq_earnings']]

    stock_importer.logger.data_dog:
        class: AppBundle\Logger\DataDogLogger
        arguments:
            - '@okvpn_datadog.client'

    stock_importer.logger.index:
        class: AppBundle\Logger\IndexLogger
        arguments:
            - '@stock_importer.repository.log'

    stock_importer.index_client_factory:
        class: AppBundle\Service\Factory\IndexClientFactory

    stock_importer.index_client:
        factory: ['@stock_importer.index_client_factory', create]
        class: Elasticsearch\Client
        arguments:
            - ['http://192.168.99.100:9200']

    stock_importer.stock_repository:
        class: AppBundle\Repository\StockRepository

    stock_importer.repository.log:
        class: AppBundle\Repository\LogRepository
        arguments:
            - '@stock_importer.index_client'
            - 'AppBundle\Model\IndexDocument\Log'

    stock_importer.repository.earnings:
        class: AppBundle\Repository\EarningsRepository
        arguments:
            - '@stock_importer.index_client'
            - 'AppBundle\Model\IndexDocument\Earnings'

    stock_importer.importer.nasdaq_earnings:
        class: AppBundle\Service\StockImporter\NasdaqEarningsImporter
        arguments:
            - '@stock_importer.repository.earnings'
