services:
    stock_importer.stock_impoter:
        class: AppBundle\Service\StockImporter
        arguments:
            - '@stock_importer.stock_repository'
        calls:
            - [setLogger,['@monolog.logger']]

    stock_importer.stock_repository:
        class: AppBundle\Repository\StockRepository
