name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./code
      
    steps:
    - name: Composer install
      uses: docker://composer
      with:
        args: install
    - name: PHPUnit testing
      uses: docker://php
      with:
        args: php vendor/bin/phpunit
